wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1676752626.423704
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.9.7
      5: 0.13.6
      8:
      - 5
batch_size:
  desc: null
  value: 5
dt:
  desc: null
  value: 1.0
mc_u:
  desc: null
  value: 1
model_hparams:
  desc: null
  value:
    Nc_uv: 1
    act_fn: jax._src.nn.functions.relu
    act_fn_name: relu
    block_size:
    - 16
    - 32
    - 64
    - 128
    - 128
    - 128
    - 128
    f_cori: "[[[0.0519269 ]\n  [0.0519269 ]\n  [0.0519269 ]\n  ...\n  [0.0519269 ]\n\
      \  [0.0519269 ]\n  [0.0519269 ]]\n\n [[0.05196775]\n  [0.05196775]\n  [0.05196775]\n\
      \  ...\n  [0.05196775]\n  [0.05196775]\n  [0.05196775]]\n\n [[0.05200859]\n\
      \  [0.05200859]\n  [0.05200859]\n  ...\n  [0.05200859]\n  [0.05200859]\n  [0.05200859]]\n\
      \n ...\n\n [[0.06701647]\n  [0.06701647]\n  [0.06701647]\n  ...\n  [0.06701647]\n\
      \  [0.06701647]\n  [0.06701647]]\n\n [[0.06705471]\n  [0.06705471]\n  [0.06705471]\n\
      \  ...\n  [0.06705471]\n  [0.06705471]\n  [0.06705471]]\n\n [[0.06709296]\n\
      \  [0.06709296]\n  [0.06709296]\n  ...\n  [0.06709296]\n  [0.06709296]\n  [0.06709296]]]"
    model_type: U_net_modified
    out_features: 4
    padding: REPLICATE
model_name:
  desc: null
  value: UNet
n_seq:
  desc: null
  value: 5
noise_level:
  desc: null
  value: '0.0'
optimizer_lr:
  desc: null
  value: 0.0001
optimizer_name:
  desc: null
  value: adam
